### ISSUE TITLE
Improve ReadMe

### ISSUE THREAD

**Issue by ratnakar5938** [ratnakar5938/Youtube-clone#10]
**Following are needed to be done** - 

- [x] Add contributors section
- [ ] Beautify the Readme
- [ ] Add Video or gif demo

**Comment by VasekS** [comment]
Hi @ratnakar5938 please assign to me! I will beautify the ReadMe section :)

**Comment by ratnakar5938** [comment]
No need to add contributions section
As all-contributors bot will do that
